from distutils.core import setup

setup(
    name='FlaskWebAppHackingDemo',
    version='0.1',
    packages=['app', 'app.views', 'app.models', 'venv.lib.python3.5.site-packages.mako',
              'venv.lib.python3.5.site-packages.mako.ext', 'venv.lib.python3.5.site-packages.click',
              'venv.lib.python3.5.site-packages.flask', 'venv.lib.python3.5.site-packages.flask.ext',
              'venv.lib.python3.5.site-packages.jinja2', 'venv.lib.python3.5.site-packages.alembic',
              'venv.lib.python3.5.site-packages.alembic.ddl', 'venv.lib.python3.5.site-packages.alembic.util',
              'venv.lib.python3.5.site-packages.alembic.script', 'venv.lib.python3.5.site-packages.alembic.runtime',
              'venv.lib.python3.5.site-packages.alembic.testing',
              'venv.lib.python3.5.site-packages.alembic.testing.plugin',
              'venv.lib.python3.5.site-packages.alembic.operations',
              'venv.lib.python3.5.site-packages.alembic.autogenerate', 'venv.lib.python3.5.site-packages.dateutil',
              'venv.lib.python3.5.site-packages.dateutil.tz', 'venv.lib.python3.5.site-packages.dateutil.zoneinfo',
              'venv.lib.python3.5.site-packages.werkzeug', 'venv.lib.python3.5.site-packages.werkzeug.debug',
              'venv.lib.python3.5.site-packages.werkzeug.contrib', 'venv.lib.python3.5.site-packages.markupsafe',
              'venv.lib.python3.5.site-packages.sqlalchemy', 'venv.lib.python3.5.site-packages.sqlalchemy.ext',
              'venv.lib.python3.5.site-packages.sqlalchemy.ext.declarative',
              'venv.lib.python3.5.site-packages.sqlalchemy.orm', 'venv.lib.python3.5.site-packages.sqlalchemy.sql',
              'venv.lib.python3.5.site-packages.sqlalchemy.util', 'venv.lib.python3.5.site-packages.sqlalchemy.event',
              'venv.lib.python3.5.site-packages.sqlalchemy.engine',
              'venv.lib.python3.5.site-packages.sqlalchemy.testing',
              'venv.lib.python3.5.site-packages.sqlalchemy.testing.suite',
              'venv.lib.python3.5.site-packages.sqlalchemy.testing.plugin',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.mssql',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.mysql',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.oracle',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.sqlite',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.sybase',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.firebird',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.postgresql',
              'venv.lib.python3.5.site-packages.sqlalchemy.databases',
              'venv.lib.python3.5.site-packages.sqlalchemy.connectors', 'venv.lib.python3.5.site-packages.flask_script',
              'venv.lib.python3.5.site-packages.flask_migrate', 'venv.lib.python3.5.site-packages.flask_sqlalchemy',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip.req',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip.vcs',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip.utils',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip.compat',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip.models',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.distlib',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.colorama',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.lockfile',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.progress',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.packaging',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.webencodings',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip.commands',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip.operations'],
    url='',
    license='MIT',
    author='Trevor Taubitz',
    author_email='trevor.taubitz@gmail.com',
    description='Basic demo of web app hacking'
)
