"""empty message

Revision ID: cda539109730
Revises: 50fc38eb98ac
Create Date: 2017-12-14 14:24:22.596485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda539109730'
down_revision = '50fc38eb98ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_username', sa.String(length=255), nullable=True),
    sa.Column('from_username', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
