"""empty message

Revision ID: e6d789ca7496
Revises: 33a15d3f3d80
Create Date: 2017-12-10 21:20:06.189660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d789ca7496'
down_revision = '33a15d3f3d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_secure_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_card_number', sa.String(length=255), nullable=True),
    sa.Column('ssn', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_card_number'),
    sa.UniqueConstraint('ssn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('super_secure_data')
    # ### end Alembic commands ###
